config/routes.rb
Rails.application.routes.draw do

  get 'foto/new'
  get 'foto/create'
  get 'foto/show'

  get  '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get  '/logout' => 'sessions#destroy'

  get 'pages/index'
  root 'pages#index'

  resources :users
  resources :produtos
  resources :fotos

  get '/ajax_m' => 'produtos#ajax_modelos'

  get 'foto_principal/:id' => 'produtos#foto_principal'
  get 'confirmar_deletar_foto/:id' => 'produtos#confirmar_deletar_foto'
  get 'deletar_foto/:id' => 'fotos#deletar'

  get '/super_led' => 'produtos#index', :categoria_id => 1
  get '/led' => 'produtos#index', :categoria_id => 2
  get '/eletronicas' => 'produtos#index', :categoria_id => 3
  get '/halogenas' => 'produtos#index', :categoria_id => 4
  get '/vapor' => 'produtos#index', :categoria_id => 5
  get '/luminarias' => 'produtos#index', :categoria_id => 6
  get '/refletores' => 'produtos#index', :categoria_id => 7

end

app/models/card.rb
class Card < ActiveRecord::Base
	has_many :users
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
	has_many :catmods
	has_many :modelos, through: :catmods

	has_many :produtos
end

app/models/catmod.rb
class Catmod < ActiveRecord::Base
  belongs_to :categoria
  belongs_to :modelo
end

app/models/foto.rb
class Foto < ActiveRecord::Base
	belongs_to :produto
	
	validates :produto, presence: true
	has_attached_file :avatar, :styles => { :medium => "400x400>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/modelo.rb
class Modelo < ActiveRecord::Base
	has_many :catmods
	has_many :categorias, through: :catmods
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  belongs_to :categoria
  belongs_to :modelo
  has_many :filhos, :class_name => "Produto", :foreign_key => "parent_id"
  belongs_to :pai, :class_name => "Produto", :foreign_key => "parent_id"
  has_many :fotos

  paginates_per 9

  validates :cod, :categoria, :modelo, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :card

  paginates_per 10
  has_secure_password

  validates :name, :email, :card, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  before_filter :set_cache_buster

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
  	redirect_to '/login' unless current_user
  end

  def render_404
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  def new
  	@foto = Foto.new
  end

  def create
    @produto = Produto.find(params[:foto][:produto_id])

    cnt = @produto.fotos.count

    # caso não tenha foto, se torna a principal
    if cnt == 0
      params[:foto][:principal] = true
    else
      params[:foto][:principal] = false
    end

    # máximo de 3 fotos por produto
    if cnt >= 3
      redirect_to @produto, :notice => 'Máximo de 3 fotos por produto'
    else
      if @foto = Foto.create(foto_params)
        @produto = @foto.produto
        redirect_to @produto, :notice => 'Foto armazenada com sucesso!'
      end
    end
  	
  end

  def show
  	@foto = Foto.find(params[:id])
  end

  def deletar
    foto = Foto.find(params[:id])
    produto = foto.produto

    # apaga a foto
    foto.destroy

    redirect_to produto, :notice => 'Foto removida com sucesso'
  end

  private

  def foto_params
	   params.require(:foto).permit(:avatar, :produto_id, :principal)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  def index
    #@produtos = Produto.order(:id).page params[:page]
    @produtos = Produto.where("categoria_id = ?", params[:categoria_id]).where(parent_id: nil).page params[:page]
    @categoria_atual = params[:categoria_id]
    @categorias = Categoria.all
    @titulo = Categoria.find(params[:categoria_id]).categoria

    @links = {
      1 => '/super_led',
      2 => '/led',
      3 => '/eletronicas',
      4 => '/halogenas',
      5 => '/vapor',
      6 => '/luminarias',
      7 => '/refletores'
    }


    @cor_destaque = Categoria.find(params[:categoria_id]).color

  end

  def foto_principal
    foto = Foto.find(params[:id])
    produto = foto.produto
    produto.fotos.each do |f|
      if f.id == foto.id
        f.principal = true
      else
        f.principal = false
      end
      f.save
    end
    
    redirect_to produto, :notice => 'Foto principal alterada'

  end

  def confirmar_deletar_foto
    @foto = Foto.find(params[:id])
    @produto = @foto.produto
  end


  def ajax_modelos
    @modelos = Categoria.find(params[:categoria_id]).modelos
    respond_to do |format|
      format.js
    end
  end

  def new
    @produto = Produto.new
    @categorias = Categoria.all
    @modelos = Categoria.first.modelos

    if !@categoria
      @categoria = Categoria.first
      @modelo = @categoria.modelos.first
    end

  end

  def create
    @produto = Produto.new(produto_params)
    @categorias = Categoria.all
    @modelos = Categoria.find(params[:produto][:categoria_id]).modelos

    @categoria = Categoria.find(params[:produto][:categoria_id])
    @modelo = Modelo.find(params[:produto][:modelo_id])

    if @produto.save
      redirect_to @produto, :notice => 'Cadastro criado com sucesso!'
    else
      render :new
    end
  end

  def show
    @produto = Produto.find(params[:id])
    @fotos = @produto.fotos
    @foto = Foto.new # para o form
  end

  def edit
    @produto = Produto.find(params[:id])
    @categorias = Categoria.all
    @categoria = @produto.categoria
    @modelos = @categoria.modelos
    @modelo = @produto.modelo

  end

  def update
    @produto = Produto.find(params[:id])

    if @produto.update_attributes(produto_params)
      redirect_to @produto, :notice => 'Cadastro alterado!'
    else
      @categorias = Categoria.all
      @categoria = @produto.categoria
      @modelos = @categoria.modelos
      @modelo = @produto.modelo
      render :edit
    end
  end

  private

  def produto_params
    params.require(:produto).permit(:cod, :categoria_id, :modelo_id, :tensao, :potencia, :cor, :bocal, :lumens, :qtd_caixa, :descricao, :preco_unitario, :preco_caixa, :preco_master ,:parent_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by_email(params[:email])

  	if @user && @user.authenticate(params[:password])
  		session[:user_id] = @user.id
  		redirect_to '/'
  	else
  		redirect_to '/login'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize

  def index
    @users = User.order(:id).page params[:page]
  end

  def show
    @user = User.find(params[:id])
 
  end

  def new
    @user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		session[:user_id] = @user.id
  		redirect_to @user, :notice => 'Cadastro criado com sucesso!'
  	else
  		render :new
  	end
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      if(current_user && current_user.card.card == "JanjaDev")
        redirect_to @user, :notice => 'Ai que delícia cara!'
      else
        redirect_to @user, :notice => 'Cadastro alterado!'
      end
    else
      render :edit
    end
  end


  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation, :card_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="uk-container uk-container-center">
		<table class='uk-margin-top'>
			<tr>
				<td style='width: 80px; text-align: center;'><i class='uk-icon-map-marker uk-icon-large'></td>
				<td>SCIA - Quadra 8 Cj8 - Cidade do Automóvel - Brasília DF</td>
			</tr>
			<tr>
				<td style='width: 80px; text-align: center;'><i class='uk-icon-phone uk-icon-large'></td>
				<td>+55 (61) 3361-1145 / 3361-2757</td>
			</tr>
			<tr>
				<td style='width: 80px; text-align: center;'><i class='uk-icon-envelope-o uk-icon-large'></td>
				<td>contato@luzsollar.com</td>
			</tr>
		</table>
	
	</div>

</div>

app/views/layouts/_navbar_off.html.erb
<nav class="uk-navbar shadow" data-uk-sticky>
    <div class='uk-container uk-container-center'>
        <a href="/" class="uk-navbar-brand uk-hidden-small"><%= image_tag('logo_branca.png') %></a>
        <% link_to root_url , class: "uk-navbar-brand uk-hidden-small" do %>
            <%= image_tag('logo_branca.png') %>
        <% end %>
        <ul class="uk-navbar-nav uk-hidden-small">
            <li><a href="">Home</a></li>
            <li data-uk-dropdown="">
                <a href="#">Produtos</a>
                <div class="uk-dropdown uk-dropdown-navbar">
                    <ul class="uk-navbar-nav uk-hidden-small tirar-escada">
                        <li><a href="/super_led">Super LED</a></li>
	                	<li class="uk-width-1-1"><a href="/led">LED</a></li>
	                	<li><a href="/fita_led">Fita LED</a></li>
	                	<li><a href="/eletronicas">Eletrônicas</a></li>
	                	<li><a href="/halogenas">Halógenas</a></li>
	                	<li><a href="/vapor">Vapor</a></li>
	                	<li><a href="/refletores">Refletores</a></li>
	                	<li><a href="/luminarias">Luminárias</a></li>
                    </ul>
                </div>
            </li>
            <li class="uk-parent"><a href="">Contato</a></li>
        </ul>

        <div class="uk-navbar-flip uk-hidden-small">
            <ul class="uk-navbar-nav">
                <li><a href="/login">login</a></li>
            </ul>
        </div>
        <a href="#offcanvas" class="uk-navbar-toggle uk-visible-small" data-uk-offcanvas></a>
        <div class="uk-navbar-brand uk-navbar-center uk-visible-small">
            <a href='/'><%= image_tag('logo_branca.png') %></a>
        </div>
    </div>
    
</nav>

<div id="offcanvas" class="uk-offcanvas">
    <div class="uk-offcanvas-bar" >
        <ul class="uk-nav uk-nav-offcanvas uk-nav-parent-icon" data-uk-nav>
        	<li class="uk-active">
                <a href="/"><i class='uk-icon-home'></i>&nbsp;&nbsp;&nbsp;Home</a>
            </li>

        	<li class="uk-parent">
                <a href="#"><i class='uk-icon-lightbulb-o'></i>&nbsp;&nbsp;&nbsp;Produtos</a>
                
                	<ul class="uk-nav-sub">
	                	<li><a href="/super_led">Super LED</a></li>
	                	<li><a href="">LED</a></li>
	                	<li><a href="">Fita LED</a></li>
	                	<li><a href="">Eletrônicas</a></li>
	                	<li><a href="">Fluorescentes</a></li>
	                	<li><a href="">Halógenas</a></li>
	                	<li><a href="">Vapor</a></li>
	                	<li><a href="">Refletores</a></li>
	                	<li><a href="">Luminárias</a></li>

	                </ul>
            </li>

            <li>
                <a href="layouts_frontpage.html"><i class='uk-icon-envelope-o'></i>&nbsp;&nbsp;&nbsp;Contato</a>
            </li>
            
            <li class="">&nbsp;</li>
            <li>
                <a href="/login"><i class='uk-icon-group'></i>&nbsp;&nbsp;&nbsp;Login</a>
            </li>
        </ul>
    </div>
</div>

app/views/layouts/_navbar_on.html.erb
<nav class="uk-navbar  my-navbar-on shadow" data-uk-sticky>
    <div class='uk-container uk-container-center'>
        <a href="/" class="uk-navbar-brand uk-hidden-small  my-navbar-on"><%= image_tag('logo_preta.png') %></a>
        <ul class="uk-navbar-nav uk-hidden-small black on">
            <li><a href="">Home</a></li>
            <li data-uk-dropdown="">
                <a href="#">ADMIN</a>
                <div class="uk-dropdown uk-dropdown-navbar">
                    <ul class="uk-navbar-nav uk-hidden-small tirar-escada">
                        <li><%= link_to "USUÁRIOS", users_path() %></li>
	                	<li><%= link_to "PRODUTOS", '/super_led' %></li>
                    </ul>
                </div>
            </li>
            <li class="uk-parent"><a href="">Contato</a></li>
        </ul>

        <div class="uk-navbar-flip uk-hidden-small">
            <ul class="uk-navbar-nav black on">
                <li data-uk-dropdown="">
                    <a href="#">Logado</a>
                    <div class="uk-dropdown uk-dropdown-navbar">
                        <ul class="uk-navbar-nav uk-hidden-small tirar-escada">
                            <li><%= link_to "PERFIL", user_path(current_user) %></li>
                            <li class="uk-width-1-1"><a href="/logout">LOGOUT</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
        <a href="#offcanvas" class="uk-navbar-toggle uk-visible-small my-navbar-on" data-uk-offcanvas></a>
        <div class="uk-navbar-brand uk-navbar-center uk-visible-small my-navbar-on">
            <a href='/'><%= image_tag('logo_preta.png') %></a>
        </div>
    </div>
    
</nav>

<div id="offcanvas" class="uk-offcanvas">
    <div class="uk-offcanvas-bar" >
        <ul class="uk-nav uk-nav-offcanvas uk-nav-parent-icon" data-uk-nav>
        	<li class="uk-active">
                <a href="/"><i class='uk-icon-home'></i>&nbsp;&nbsp;&nbsp;Home</a>
            </li>

        	<li class="uk-parent">
                <a href="#"><i class='uk-icon-lightbulb-o'></i>&nbsp;&nbsp;&nbsp;Produtos</a>
                
                	<ul class="uk-nav-sub">
	                	<li><a href="/super_led">Super LED</a></li>
	                	<li><a href="/led">LED</a></li>
	                	<li><a href="/fita_led">Fita LED</a></li>
	                	<li><a href="/eletronicas">Eletrônicas</a></li>
	                	<li><a href="/halogenas">Halógenas</a></li>
	                	<li><a href="/vapor">Vapor</a></li>
	                	<li><a href="/refletores">Refletores</a></li>
	                	<li><a href="/luminarias">Luminárias</a></li>

	                </ul>
            </li>

            <li>
                <a href="layouts_frontpage.html"><i class='uk-icon-envelope-o'></i>&nbsp;&nbsp;&nbsp;Contato</a>
            </li>
            
            <li class="">&nbsp;</li>
            <li>
                <a href="/logout"><i class='uk-icon-group'></i>&nbsp;&nbsp;&nbsp;Logout</a>
            </li>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Luzsollar</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<div class='page-wrap'>

	<% if current_user %>
	    <%= render 'layouts/navbar_on' %>
	<% else %>
	    <%= render 'layouts/navbar_off' %>
	<% end %>

	<%= yield %>

</div>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/modelos/_modelo.html.erb
<option value="<%= modelo.id %>"><%= modelo.modelo.titleize %></option>

app/views/pages/index.html.erb
<div class="spacer"></div>
<div id="banner">
<ul class="uk-slideshow" data-uk-slideshow="{autoplay:true, autoplayInterval:5000}">
    <li>
    	<div class='banner1-lg'><%= image_tag('banners/banner1-1440x700.png')%></div>
    	<div class='banner1-md'><%= image_tag('banners/banner1-960x700.png')%></div>
    	<div class='banner1-sm'><%= image_tag('banners/banner1-768x700.png')%></div>
    	<div class='banner1-xs'><%= image_tag('banners/banner1-480x700.png')%></div>
    </li>
    <li>
    	<div class='banner2-lg'><%= image_tag('banners/banner2-1440x700.png')%></div>
    	<div class='banner2-md'><%= image_tag('banners/banner2-960x700.png')%></div>
    	<div class='banner2-sm'><%= image_tag('banners/banner2-768x700.png')%></div>
    	<div class='banner2-xs'><%= image_tag('banners/banner2-480x700.png')%></div>
    </li>
    <li>
    	<div class='banner3-lg'><%= image_tag('banners/banner3-1440x700.png')%></div>
    	<div class='banner3-md'><%= image_tag('banners/banner3-960x700.png')%></div>
    	<div class='banner3-sm'><%= image_tag('banners/banner3-768x700.png')%></div>
    	<div class='banner3-xs'><%= image_tag('banners/banner3-480x700.png')%></div>
    </li>
   
</ul>
</div>

app/views/produtos/_sidebar_produtos.html.erb
<ul class="uk-nav uk-nav-side">
	<% @categorias.each do |cat| %>

    	<li class="<% if cat.id == @categoria_atual %>uk-active<% else %> hover-<%=cat.id%><% end %>"><a style="<% if cat.id == @categoria_atual %>background-color: <%= @cor_destaque %><% end %>" href="<%= @links[cat.id]%>"><%= cat.categoria %></a></li>
    <% end %>
</ul>

app/views/produtos/confirmar_deletar_foto.html.erb
<div class="spacer"></div>
<div class="uk-container uk-container-center uk-margin-top">
	<h1>Deletar foto</h1>
	<%= image_tag @foto.avatar.url(:thumb) %>
	<p>Deseja realmente deletar a foto? Clique <%= link_to "aqui", :controller => "fotos", :action => "deletar", :id => @foto.id %></p>
	<p><%= link_to "Voltar", @produto %> para produto: <%= @produto.cod %></p>
</div>

app/views/produtos/create.html.erb
<h1>Produtos#create</h1>
<p>Find me in app/views/produtos/create.html.erb</p>

app/views/produtos/edit.html.erb
<div class="spacer"></div>
<div class='uk-container uk-container-center uk-margin-top'>
<h1 class='uk-margin-top'>Editar Produto</h1>
<%= render "form" %>

</div>

app/views/produtos/index.html.erb
<div class="spacer"></div>
<div class='uk-container uk-container-center uk-margin-top'>
	<h1 class='uk-margin-top' style='color: <%=@cor_destaque%>'><%= @titulo %></h1>
	<br/>
	<div class='uk-grid uk-margin-top'>
		<div class='uk-width-1-1 uk-width-medium-3-4'>
			<div class='uk-grid' data-uk-grid-margin>

				<% @produtos.each do |p|%>
				<div class='uk-width-1-1 uk-width-medium-1-2 uk-width-large-1-3 uk-text-center'>
					<div class='uk-width-1-1'>
						<%= link_to p do %>
							<% if p.fotos.count >= 1 %>
								<% p.fotos.each do |f| %>
									<% if f.principal %>
										<%= image_tag f.avatar.url(:medium) %>
									<% end %>
								<% end %>
								
							<% else %>
								<%= image_tag 'prod-default.png' %>
							<% end %>
						<% end %>
						<div class='card-desc'><h3 style='color: <%=@cor_destaque%>'><%= p.modelo.modelo %></h3></div>
						<div class='card-campos'><%= p.potencia %></div>
						<div class='card-campos'><%= p.cor %></div>
						<div class='card-campos'><%= p.tensao %></div>
					</div>
				</div>
				<% end %>

			</div>
			<br/>
			<br/>
		</div>


		<div class='uk-width-1-1 uk-width-medium-1-4'>
			<%= render 'sidebar_produtos' %>

			<br/><br/>
			<% if current_user %>
			<%= link_to new_produto_path(), class: "uk-button uk-button-large uk-button-success" do %><i class='uk-icon-lightbulb-o'></i>&nbsp;NOVO PRODUTO<% end %>
			<br/><br/>
			<% end %>

		</div>
	</div>

	
	<%= paginate @produtos %>
</div>

app/views/produtos/new.html.erb
<div class="spacer"></div>
<div class='uk-container uk-container-center uk-margin-top'>
<h1 class='uk-margin-top'>Novo Produto</h1>
<%= render "form" %>

</div>

app/views/produtos/show.html.erb
<div class="spacer"></div>
<div class="uk-container uk-container-center uk-margin-top">
	<h1 class='uk-margin-top' style="color: <%= @produto.categoria.color %>"><%= @produto.categoria.categoria %> - <%=@produto.modelo.modelo %></h1>

	<% if notice %>
		<div class="uk-alert"><%= notice %></div>
	<% end %>
	
	<div class='uk-grid'>
		<div class='uk-width-1-1 '>
			<div class="" style="height: 256px; float: left;">
				<% if @fotos.count >= 1 %>
					<% @fotos.each do |f| %>
						<% if f.principal %>
							<%= image_tag f.avatar.url(:medium), :class => "produto-img-destaque" %>
						<% end %>
					<% end %>
				<% end %>
			</div>
			
		
			<div class='thumbs'>
				<% @fotos.each do |f| %>
					<%= image_tag f.avatar.url(:thumb) %>
				<% end %>
			</div>
			
		</div>
	</div>
	<div class='uk-grid'>
		<div class='uk-width-1-1'>
		
			<table class="uk-table uk-table-striped">
				<tr>
					<th>COD</th>
					<th>TENSÃO</th>
					<th>POTÊNCIA</th>
					<th>COR</th>
				</tr>
				<tr>
					<td><%= @produto.cod%></td>
					<td><%= @produto.tensao%></td>
					<td><%= @produto.potencia%></td>
					<td><%= @produto.cor%></td>
				</tr>

				<% @produto.filhos.each do |fi| %>
				<tr>
					<td><%= fi.cod %></td>
					<td><%= fi.tensao %></td>
					<td><%= fi.potencia %></td>
					<td><%= fi.cor %></td>
				</tr>
				<% end %>
				

			</table>
		</div>
	</div>

	<br/><br/>
	<% if current_user %>

		<h2>Administração</h2>
		<hr/>

		<h4>FOTOS</H4>
	
		<div class="uk-clearfix">
		<% @fotos.each do |f| %>
			<div style="width: 100px; float:left; margin: 0 20px;" class="uk-text-center">
				<%= image_tag f.avatar.url(:thumb) %>
				<% if f.principal %>
				principal
				<% else %>
				<%= link_to "tornar principal", :action => "foto_principal", :id => f.id %>

				<% end %>
				<br/>
				<%= link_to "deletar", :action => "confirmar_deletar_foto", :id => f.id %>
			</div>
		<% end %>
		</div>
		<br/><br/><br/>


		<%= form_for @foto, :url => fotos_path, :html => { :multipart => true } do |f| %>
		  <%= f.hidden_field :produto_id, {:value => @produto.id} %>
		  <%= f.file_field :avatar %>

		 <br/><br/>
		 <%= f.submit "Click",  :class => "uk-button uk-button-primary"%>
		<% end %>


		<!-- produto pai -->

		<br/><br/>
		
		<% if @produto.filhos.count == 0 %>
			<h2>Produto Pai</h2>
			<% if @produto.pai == nil %>
				<!-- form para pai -->
				<%= form_for @produto, html: {class: "uk-form uk-form-stacked"} do |f| %>
					<%= collection_select(:produto, :parent_id, Produto.where("categoria_id = ?", @produto.categoria.id).where("modelo_id = ?", @produto.modelo.id).where("id != ?", @produto.id), :id, :cod)%>
					<button class='uk-button uk-button-primary'><i class='uk-icon-check'></i>&nbsp;ASSOCIAR</button>
				<% end %>

			<% else %>
				<!-- exibe o pai e link para desfazer -->
				<%= link_to @produto.pai.cod, produto_path(@produto.pai) %>
				<%= form_for @produto, html: {class: "uk-form uk-form-stacked"} do |f| %>
					<%= f.hidden_field :parent_id, {:value => nil} %>
					<button class='uk-button uk-button-primary'><i class='uk-icon-check'></i>&nbsp;DESFAZER</button>
				<% end %>

			<% end %>

		<% end %>
		<br/>
		<br/>

	<% end %>

</div>

app/views/produtos/update.html.erb
<h1>Produtos#update</h1>
<p>Find me in app/views/produtos/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<div class="spacer"></div>
<div class='uk-container uk-container-center uk-margin-top'>
	<h1 class='uk-margin-top'>Lista de Usuários</h1>

	<table class='uk-table uk-table-hover uk-table-striped'>
		<thead>
			<th>NOME</th>
			<th>ACESSO</th>
			<th class='uk-text-center'>EDITAR</th>
		</thead>
		<tbody>
			<% @users.each do |u| %>
				<tr>
					<td><%= u.name %></td>
					<td><%= u.card.card %></td>
					<td class='uk-text-center'><%=link_to edit_user_path(u) do%> <i class='uk-icon-edit'></i> <% end %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<br/>

	<%= link_to new_user_path(), class: "uk-button uk-button-success uk-button-large" do %><i class='uk-icon-user'></i>&nbsp;CADASTRAR NOVO<% end %>
	<br/><br/>
	<%= paginate @users %>
</div>

app/views/users/show.html.erb
<div class='spacer'></div>
<div class="uk-container uk-container-center uk-margin-top">
	<% if notice %>
		<div class="uk-alert"><%= notice %></div>
	<% end %>
	<h1 class='uk-margin-top'><%= @user.name %></h1>
	<p><%= @user.card.card %></p>
	<p><%= @user.email %></p>
	<%= link_to edit_user_path(@user) do%> 
		<i class='uk-icon-edit'></i>&nbsp;EDITAR
	<% end %>
	<br/>

</div>